"""Audit event types for claim_audit_log.

Standardized event types for compliance and querying. All audit records are
append-only (no UPDATE or DELETE). See docs/database.md for schema and retention.
"""

# Event types (action column)
AUDIT_EVENT_CREATED = "created"
AUDIT_EVENT_STATUS_CHANGE = "status_change"
AUDIT_EVENT_APPROVAL = "approval"
AUDIT_EVENT_REJECTION = "rejection"
AUDIT_EVENT_REPROCESS = "reprocess"
AUDIT_EVENT_ESCALATION = "escalation"
AUDIT_EVENT_PAYOUT_SET = "payout_set"
AUDIT_EVENT_ATTACHMENTS_UPDATED = "attachments_updated"
AUDIT_EVENT_REQUEST_INFO = "request_info"
AUDIT_EVENT_ESCALATE_TO_SIU = "escalate_to_siu"
AUDIT_EVENT_SIU_CASE_CREATED = "siu_case_created"
AUDIT_EVENT_ASSIGN = "assign"
AUDIT_EVENT_RETENTION = "retention_archived"
AUDIT_EVENT_RETENTION_PURGED = "retention_purged"
AUDIT_EVENT_FOLLOW_UP_SENT = "follow_up_sent"
AUDIT_EVENT_FOLLOW_UP_RESPONSE = "follow_up_response"
AUDIT_EVENT_CLAIM_REVIEW = "claim_review"
AUDIT_EVENT_TASK_CREATED = "task_created"
AUDIT_EVENT_TASK_UPDATED = "task_updated"
AUDIT_EVENT_RESERVE_SET = "reserve_set"
AUDIT_EVENT_RESERVE_ADJUSTED = "reserve_adjusted"
AUDIT_EVENT_PAYMENT_AUTHORIZED = "payment_authorized"
AUDIT_EVENT_PAYMENT_ISSUED = "payment_issued"
AUDIT_EVENT_PAYMENT_CLEARED = "payment_cleared"
AUDIT_EVENT_PAYMENT_VOIDED = "payment_voided"
AUDIT_EVENT_COVERAGE_VERIFICATION = "coverage_verification"
AUDIT_EVENT_ACKNOWLEDGED = "ucspa_acknowledged"
AUDIT_EVENT_DENIAL_LETTER = "denial_letter_sent"
AUDIT_EVENT_LITIGATION_HOLD = "litigation_hold"

# Actor identifiers for automated actions
ACTOR_SYSTEM = "system"
ACTOR_WORKFLOW = "workflow"
ACTOR_RETENTION = "retention"

# All event types (for validation/docs)
AUDIT_EVENT_TYPES = (
    AUDIT_EVENT_CREATED,
    AUDIT_EVENT_STATUS_CHANGE,
    AUDIT_EVENT_APPROVAL,
    AUDIT_EVENT_REJECTION,
    AUDIT_EVENT_REPROCESS,
    AUDIT_EVENT_ESCALATION,
    AUDIT_EVENT_PAYOUT_SET,
    AUDIT_EVENT_ATTACHMENTS_UPDATED,
    AUDIT_EVENT_REQUEST_INFO,
    AUDIT_EVENT_ESCALATE_TO_SIU,
    AUDIT_EVENT_SIU_CASE_CREATED,
    AUDIT_EVENT_ASSIGN,
    AUDIT_EVENT_RETENTION,
    AUDIT_EVENT_RETENTION_PURGED,
    AUDIT_EVENT_FOLLOW_UP_SENT,
    AUDIT_EVENT_FOLLOW_UP_RESPONSE,
    AUDIT_EVENT_CLAIM_REVIEW,
    AUDIT_EVENT_TASK_CREATED,
    AUDIT_EVENT_TASK_UPDATED,
    AUDIT_EVENT_RESERVE_SET,
    AUDIT_EVENT_RESERVE_ADJUSTED,
    AUDIT_EVENT_PAYMENT_AUTHORIZED,
    AUDIT_EVENT_PAYMENT_ISSUED,
    AUDIT_EVENT_PAYMENT_CLEARED,
    AUDIT_EVENT_PAYMENT_VOIDED,
    AUDIT_EVENT_COVERAGE_VERIFICATION,
    AUDIT_EVENT_ACKNOWLEDGED,
    AUDIT_EVENT_DENIAL_LETTER,
    AUDIT_EVENT_LITIGATION_HOLD,
)
