"""SQLite DDL for the rental_authorizations table.

``rental_authorizations`` stores structured rental authorization records
persisted when the rental crew completes.  Each row captures:

- ``reservation_ref`` – vendor reservation number (internal; not exposed to portal)
- ``agency_ref``       – rental agency reference (internal; not exposed to portal)
- ``authorized_days``  – number of days approved under the policy
- ``daily_cap``        – per-day limit in USD from the policy
- ``direct_bill``      – 1 = carrier direct-bills the agency; 0 = claimant reimbursed
- ``status``           – authorized | in_progress | completed | cancelled
- ``reimbursement_id`` – RENT-* ID generated by rental_logic (idempotency key)
- ``amount_approved``  – total amount approved (capped by daily_cap * days and
                         aggregate_limit)

The portal DTO (``GET /api/portal/claims/{claim_id}/rental-summary``) omits ``reservation_ref``
and ``agency_ref`` which are internal/vendor-sensitive, and exposes only the
structured fields a claimant needs to understand their rental entitlement.

PostgreSQL equivalents use ``TIMESTAMPTZ`` for temporal columns and ``SERIAL``
for the PK; keep columns and nullability aligned when changing schema here.
"""

RENTAL_AUTHORIZATIONS_TABLE_SQLITE = """CREATE TABLE IF NOT EXISTS rental_authorizations (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    claim_id TEXT NOT NULL,
    reservation_ref TEXT,
    agency_ref TEXT,
    authorized_days INTEGER NOT NULL,
    daily_cap REAL NOT NULL,
    direct_bill INTEGER NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'authorized',
    reimbursement_id TEXT,
    amount_approved REAL,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),
    FOREIGN KEY (claim_id) REFERENCES claims(id),
    CHECK (status IN ('authorized', 'in_progress', 'completed', 'cancelled'))
)"""

IDX_RENTAL_AUTH_CLAIM_ID = (
    "CREATE INDEX IF NOT EXISTS idx_rental_authorizations_claim_id "
    "ON rental_authorizations(claim_id)"
)

IDX_RENTAL_AUTH_REIMBURSEMENT_ID = (
    "CREATE UNIQUE INDEX IF NOT EXISTS idx_rental_authorizations_reimbursement_id "
    "ON rental_authorizations(reimbursement_id) WHERE reimbursement_id IS NOT NULL"
)
